### ISSUE TITLE
Doq generates HTML with block elements inside paragraphs

### ISSUE THREAD

**Issue by ghost** [rxi/doq#1]
First of all, thank you for your work. _microui_, _lite_, _aq_, _doq_ are incredible things!

I like doq but it has a small issue with handling of paragraphs.

The html standard [says](https://www.w3.org/TR/html401/struct/text.html#h-9.3.1):

> The P element represents a paragraph. It **cannot contain block-level elements** (including P itself).

Unfortunately doq generates HTML with H*, UL, PRE and other block elements inside paragraphs (P).

**Comment by rxi** [comment]
Thanks for the kind words!

In the case of `doq` I've approached it with "absolute minimalism", and, so long as the document renders correctly in browsers it will be likely viewed in, am not too concerned with being standards compliant. Note this isn't how I'd usually approach projects but in the case of `doq` I'm opting to have a simpler implementation as opposed to outputting *strictly correct* HTML.
